- name: "Run all role tasks for Linux"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    default_tarsnap_config_file_path: "{{ linux_tarsnap_config_file_path }}"
    default_machine_key_path: "{{ linux_machine_key_path }}"
    default_acts_config_file_path: "{{ linux_acts_config_file_path }}"
    default_acts_program_path: "{{ linux_acts_program_path }}"
  when: ansible_system == "Linux"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    default_tarsnap_config_file_path: "{{ freebsd_tarsnap_config_file_path }}"
    default_machine_key_path: "{{ freebsd_machine_key_path }}"
    default_acts_config_file_path: "{{ freebsd_acts_config_file_path }}"
    default_acts_program_path: "{{ freebsd_acts_program_path }}"
  when: ansible_os_family == "FreeBSD"

