- name: "Install and configure cron daemon dependency"
  ansible.builtin.include_role:
    name: ext/ans_role_config_cron

- name: "Install 'acts' tarsnap backup script"
  ansible.builtin.include_role:
    name: ans_role_config_unofficial_packages
    tasks_from: inc/add_package.yml
  vars:
    package_name: "acts-git"

