- name: "Configure 'acts' script settings, and backup paths, in {{ default_acts_config_file_path }}"
  ansible.builtin.template:
    dest: "{{ default_acts_config_file_path }}"
    src: "acts_conf.j2"
    owner: 'root'
    mode: '644'
    force: yes
  become: true
  become_user: root

- name: "Configure cron to run 'acts' daily, at the hour of {{ daily_automatic_backup_hour }}"
  ansible.builtin.cron:
    name: 'tarsnap acts auto-backup'
    hour: "{{ daily_automatic_backup_hour }}"
    minute: '0'
    user: 'root'
    job: "{{ default_acts_program_path }}"
  become: true
  become_user: root

