- name: "Install and configure cron daemon dependency"
  ansible.builtin.include_role:
    name: ext/ans_role_config_cron

- name: "Install 'acts' tarsnap backup script"
  ansible.builtin.include_role:
    name: ans_role_config_unofficial_packages
    tasks_from: inc/add_package.yml
  vars:
    package_name: "acts-git"

- name: "Configure 'acts' script settings, and backup paths, in '/etc/acts.conf'"
  ansible.builtin.template:
    dest: '/etc/acts.conf'
    src: "acts_conf.j2"
    owner: 'root'
    group: 'root'
    mode: '644'
    force: yes
  become: true
  become_user: root

- name: "Configure cron to run 'acts' daily, at the hour of {{ daily_automatic_backup_hour }}"
  ansible.builtin.cron:
    name: 'tarsnap acts auto-backup'
    hour: "{{ daily_automatic_backup_hour }}"
    minute: '0'
    user: 'root'
    job: '/usr/bin/acts'
  become: true
  become_user: root

