- name: "Configure default Tarsnap app settings in '/etc/tarsnap/tarsnap.conf'"
  ansible.builtin.template:
    dest: '/etc/tarsnap/tarsnap.conf'
    src: "tarsnap_conf.j2"
    owner: 'root'
    group: 'root'
    mode: '644'
    force: yes
  become: true
  become_user: root

