- name: "Configure default Tarsnap app settings in '{{ default_tarsnap_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ default_tarsnap_config_file_path }}"
    src: "tarsnap_conf.j2"
    owner: 'root'
    mode: '644'
    force: yes
  become: true
  become_user: root

