- name: "Create '/usr/local/bin/do_tarsnap.sh' utility script"
  ansible.builtin.template:
    dest: "/usr/local/bin/do_tarsnap.sh"
    src: "do_tarsnap.j2"
    owner: 'root'
    mode: '755'
    force: yes
  become: true
  become_user: root

